changing segment_items to improve performance
fastaudio/fastai_audio pull request #40
Opened 2019-08-20 21:19 UTC by kevinbird15

I believe this will speed up reruns when segmenting items.  Basically instead of loading every file, I just look at the sample rate in the config and then move the loading to inside the if that checks if the file is already there.

2019-08-21 12:28 UTC, rbracco requested changes
Looks good. My only concern was that config._sr could end up as None but I checked and it is always set before this point in the code so it's good to go.

2019-08-21 12:28 UTC, rbracco commented on audio/data.py
> +    segsize = int(config._sr*config.segment_size/1000)
Why not move this inside the block as well?

2019-08-21 13:23 UTC, rbracco approved these changes

2019-09-01 11:28 UTC, mogwai commented
Good find. I think that originally we were using the the loaded sr from the file to calculate the cache file uri but now that is configured in the config._sr we don't need to load it.

2019-09-01 11:28 UTC, merged